name: Build Electron App

on:
  push:
    branches:
      - release
  pull_request:
    branches:
      - release

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.2'

      - name: Install dependencies
        run: npm install

      - name: Build for Mac ARM64
        run: npm run make -- --arch=arm64

      - name: Upload Mac ARM64 build
        uses: actions/upload-artifact@v4
        with:
          name: mac-arm64-build
          path: out/make/zip/darwin-arm64

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.2'

      - name: Install dependencies
        run: npm install

      - name: Build for Windows
        run: npm run make -- --arch=ia32

      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: out/make/squirrel.windows/ia32